<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Ubuntu:wght@700&display=swap" rel="stylesheet">
        
        <link rel="stylesheet" href="http://localhost/PHP/coda-bph-2025-projet-2/assets/styles/style.css">
    </head>
    <body>
        <header>
            <main>
                <?php
                    require "templates/partials/_header.phtml";
                ?> 
            </main>
        </header>
    </body>
</html>