<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <title>The League</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Ubuntu:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/styles/style.css?v=<?= time() ?>">
</head>

<body>
    <?php require "templates/partials/_header.phtml"; ?>

    <main>
        <?php 
            // Si le routeur a défini un template, on l'inclut sinon pas grave chillll
            if($template !== null && file_exists("templates/" . $template . ".phtml")) {
                require "templates/" . $template . ".phtml";
            } else {
                echo "<h1>Page introuvable ou en construction (Template : $template)</h1>";
            }
        ?>
    </main>
</body>
</html>